const imagePath = {
  Union: require('../assests/Union.png'),
  team: require('../assests/team.png'),
  home: require('../assests/home.png'),
  lead: require('../assests/lead.png'),
  categorie: require('../assests/categorie.png'),
  default_img: require('../assests/default_img.png'),
  bonus: require('../assests/bonus.png'),
  scratch: require('../assests/scratch.png'),
  banner: require('../assests/banner.png'),
  EnglishSoftSkills: require('../assests/EnglishSoftSkills.png'),
  filter_i: require('../assests/filter_i.png'),
  Insurance: require('../assests/Insurance.png'),
  keyboard: require('../assests/keyboard.png'),
  mouse_o: require('../assests/mouse_o.png'),
  mouse_w: require('../assests/mouse_w.png'),
  mouse: require('../assests/mouse.png'),
  Online_courses: require('../assests/Online_courses.png'),
  ResumeInterviewPrep: require('../assests/ResumeInterviewPrep.png'),
  Tech_job_training: require('../assests/Tech_job_training.png'),
  NextButton: require('../assests/NextButton.png'),
  notifi: require('../assests/notifi.png'),
  music: require('../assests/music.png'),
  product_1: require('../assests/product_1.png'),
  product_2: require('../assests/product_2.png'),
  money_saving: require('../assests/money-saving.png'),
};

export default imagePath;
