const WELCOME_DATA = 'WELCOME_DATA';
const DESTINATION = 'DESTINATION';
const CURRENT_DESTINATION = 'CURRENT_DESTINATION';
const MANGE_HOME_PROPS = 'MANGE_HOME_PROPS';
const OTHER_MOBILITY_EQUIPMENT = 'OTHER_MOBILITY_EQUIPMENT';
const SCHEDULE_RIDE_DATE = 'SCHEDULE_RIDE_DATE';
const FIND_DRIVER_DATA = 'FIND_DRIVER_DATA';
const RIDE_CANCEL_DATA_STORE = 'RIDE_CANCEL_DATA_STORE';
const UPDATE_FAVORITE_LIST = 'UPDATE_FAVORITE_LIST';
const ACCEPT_RIDE_STORE = 'ACCEPT_RIDE_STORE';
const DISTANCE_TIME = 'DISTANCE_TIME';

export {
  WELCOME_DATA,
  DESTINATION,
  CURRENT_DESTINATION,
  MANGE_HOME_PROPS,
  OTHER_MOBILITY_EQUIPMENT,
  SCHEDULE_RIDE_DATE,
  FIND_DRIVER_DATA,
  RIDE_CANCEL_DATA_STORE,
  UPDATE_FAVORITE_LIST,
  ACCEPT_RIDE_STORE,
  DISTANCE_TIME,
};
